# Generated by Django 5.1.3 on 2024-11-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введиет название компании или имя ч/л', max_length=100, verbose_name='Имя/Название')),
                ('phone', models.CharField(help_text='Введите номер телефона для связи', max_length=30, verbose_name='Номер телефона')),
                ('date', models.DateField(help_text='Введите дату начала арендного срока', verbose_name='Дата начала арендного срока')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование баллона', max_length=50, verbose_name='Наименование баллона')),
                ('age_group', models.CharField(choices=[('under_5_ru', 'Моложе 5 лет, РФ'), ('under_5_ch', 'Моложе 5 лет, Китай'), ('over_5_ru', 'Старше 5 лет РФ'), ('over_5_ch', 'Старше 5 лет Китай')], max_length=10, verbose_name='Вид тары')),
                ('count', models.IntegerField(help_text='Введите количество баллонов', verbose_name='Количество')),
                ('duration', models.CharField(blank=True, help_text='Предположительный срок арены', max_length=255, null=True, verbose_name='Срок аренды')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.company', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Баллон',
                'verbose_name_plural': 'Баллоны',
            },
        ),
    ]
