# Generated by Django 5.1.3 on 2024-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='count',
        ),
        migrations.AddField(
            model_name='container',
            name='count_shipped',
            field=models.IntegerField(blank=True, help_text='Введите количество отгруженых баллонов', null=True, verbose_name='Количество отгружено'),
        ),
        migrations.AddField(
            model_name='container',
            name='count_taken',
            field=models.IntegerField(blank=True, help_text='Введите количество принятых баллонов', null=True, verbose_name='Количество принято'),
        ),
    ]
