# Generated by Django 5.1.3 on 2024-11-15 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_remove_container_count_container_count_shipped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date',
        ),
        migrations.AddField(
            model_name='container',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Введите дату', verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
